[theme]
primaryColor = "#4CAF50"
backgroundColor = "#1a1a1a"
secondaryBackgroundColor = "#2d2d2d"
textColor = "#ffffff"

[server]
port = 8501
address = "localhost"
maxUploadSize = 200

[browser]
gatherUsageStats = false
